
#!/bin/bash

echo "🐳 Construyendo la imagen Docker..."
docker-compose build

echo "🚀 Iniciando el contenedor..."
docker-compose up -d

echo "⏳ Esperando que los servicios estén listos..."
sleep 15

echo "✅ Aplicación desplegada exitosamente!"
echo ""
echo "🌐 URLs disponibles:"
echo "  - Aplicación: http://localhost:3000"
echo "  - Supabase Studio: http://localhost:3002"
echo "  - API REST: http://localhost:8080/rest/v1/"
echo "  - Realtime: ws://localhost:8080/realtime/v1/"
echo "  - Base de datos: postgresql://postgres:your-super-secret-and-long-postgres-password@localhost:5432/postgres"
echo ""
echo "👤 Credenciales de administrador:"
echo "  - Usuario: admin"
echo "  - Contraseña: 12345678"
echo "  - Rol: admin"
echo ""
echo "📊 Datos iniciales incluidos:"
echo "  - Usuario admin configurado"
echo "  - 4 Prensas configuradas"
echo "  - 6 Botones de alerta configurados"
echo ""
echo "🎛️ Supabase Studio:"
echo "  - Accede a http://localhost:3002 para administrar la base de datos"
echo "  - Interface web completa para gestionar tablas, datos y consultas"
echo ""
echo "🔄 Tiempo real activado para:"
echo "  - Alertas (automático)"
echo "  - Prensas (automático)"
echo ""
echo "Comandos útiles:"
echo "  - Ver logs: docker-compose logs -f"
echo "  - Ver logs específicos: docker-compose logs -f [servicio]"
echo "  - Parar aplicación: docker-compose down"
echo "  - Reiniciar: docker-compose restart"
echo "  - Limpiar todo: docker-compose down -v"
echo ""
echo "🗃️ Para acceder a Studio:"
echo "  1. Abre http://localhost:3002"
echo "  2. Usa la URL del proyecto: http://localhost:8080"
echo "  3. API Key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"
